theme = "ayu_darker"

[editor]
cursorline = true
cursorcolumn = true
bufferline = "always"
text-width = 120
rulers = [121]
auto-pairs = false
true-color = true

# [editor.soft-wrap]
# enable = true

[editor.file-picker]
hidden = false

[keys.normal]
# shrink line up with Shift-X
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
# H = "move_prev_sub_word_start"
# L = "move_next_sub_word_start"

[keys.select]
# shrink line up with Shift-X
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
# better selection
# H = "extend_prev_sub_word_start"
# L = "extend_next_sub_word_start"
