[language-server.rust-analyzer]
config = { cargo = { features = "all" } }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = [ "clangd", "harper-ls" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "harper-ls" ]

