[language-server.rust-analyzer]
config = { cargo = { features = "all" } }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "markdown"
language-servers = [ "marksman", "harper-ls" ]

