add_newline = false
format="$username$hostname$git_branch$status$directory> "

palette = "ayu_dark"

# Ayu dark from helix
[palettes.ayu_dark]
background = "#0f1419"
foreground = "#bfbdb6"
black = "#131721"
blue = "#59c2ff"
dark_gray = "#2d3640"
cyan = "#73b8ff"
gray = "#5c6773"
green = "#aad94c"
magenta = "#d2a6ff"
orange = "#ff8f40"
red = "#f07178"
yellow = "#e6b450"

[hostname]
ssh_only = false
format =  "[$hostname](blue) "
trim_at = ".companyname.com"
disabled = false

[git_branch]
style = "fg:magenta"

[username]
style_user = "white"
style_root = "black"
format = "[$user]($style)@"
disabled = false
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[cmd_duration]
disabled = true

[time]
disabled = false
style = "bright-black"
format = "[$time]($style)"

[line_break]
disabled = true

[status]
format = "[!](red)[$status]($style) "
disabled = false
