add_newline = false
format="$username$hostname$git_branch$git_commit$git_state$status$directory> "

palette = "onenord"

# Define custom colors
[palettes.onenord]
fg = "#C8D0E0"
fg_light = "#E5E9F0"
bg = "#2E3440"
gray = "#646A76"
light_gray = "#6C7A96"
cyan = "#88C0D0"
blue = "#81A1C1"
dark_blue = "#5E81AC"
green = "#A3BE8C"
light_green = "#8FBCBB"
dark_red = "#BF616A"
red = "#D57780"
light_red = "#DE878F"
pink = "#E85B7A"
dark_pink = "#E44675"
orange = "#D08F70"
yellow = "#EBCB8B"
purple = "#B988B0"
light_purple = "#B48EAD"
none = "NONE"

[hostname]
ssh_only = false
format =  "[$hostname](bold blue) "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)@"
disabled = false
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[status]
format = "[!](red)[$status]($style) "
disabled = false
