add_newline = true
format="$all$directory$character"

[hostname]
ssh_only = false
format =  "[$hostname](bold blue) "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)@"
disabled = false
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = false

[cmd_duration]
disabled = true

[python]
disabled = true
